name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.69.0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.RUST_VERSION }}
        target: wasm32-unknown-unknown
        override: true
        profile: minimal
    - name: Install trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'
    - name: Build
      run: trunk build
    - name: Run tests
      run: cargo test --verbose
